# Generated by Django 3.0.6 on 2020-05-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dream', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Dream',
                'verbose_name_plural': 'Dreams',
            },
        ),
    ]
